apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: fintech-gateway
  namespace: fintech-app
spec:
  selector:
    istio: ingressgateway # use Istio's built-in ingress gateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: api-gateway-vs
  namespace: fintech-app
spec:
  hosts:
  - "*"
  gateways:
  - fintech-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: api-gateway
        port:
          number: 8080
